---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUAN3GB5ZOUkVIlLhHW3fTQtBYSWAwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMTIzMTEzMzAwWhcNMzUxMTIwMTEzMzAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCgm
          guB9JpHW7DKcNFh9Ufi2P2DGV4u1T2hkhg8aUUiEluIvLTIGLO5IBC9qg2uaCrk7
          XQW9grx1rQNN0h/DUzmjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBQLCJLiN2O2plsu2/8A6vqvh0hPMjAKBggqhkjOPQQD
          AgNHADBEAiBN4qOtzNTAqDEjq55DUqdeUQQaLy6yHi5n2sW0GP97iwIgENsOkTn3
          XU5CAJB66DDtt4/UHmWUyN6eRwHDokJE2Qs=
          -----END CERTIFICATE-----

    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
  peer1.org1.example.com:
    url: grpcs://localhost:${P1PORT}
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUAN3GB5ZOUkVIlLhHW3fTQtBYSWAwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMTIzMTEzMzAwWhcNMzUxMTIwMTEzMzAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCgm
          guB9JpHW7DKcNFh9Ufi2P2DGV4u1T2hkhg8aUUiEluIvLTIGLO5IBC9qg2uaCrk7
          XQW9grx1rQNN0h/DUzmjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBQLCJLiN2O2plsu2/8A6vqvh0hPMjAKBggqhkjOPQQD
          AgNHADBEAiBN4qOtzNTAqDEjq55DUqdeUQQaLy6yHi5n2sW0GP97iwIgENsOkTn3
          XU5CAJB66DDtt4/UHmWUyN6eRwHDokJE2Qs=
          -----END CERTIFICATE-----

    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      hostnameOverride: peer1.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUAN3GB5ZOUkVIlLhHW3fTQtBYSWAwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMTIzMTEzMzAwWhcNMzUxMTIwMTEzMzAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCgm
          guB9JpHW7DKcNFh9Ufi2P2DGV4u1T2hkhg8aUUiEluIvLTIGLO5IBC9qg2uaCrk7
          XQW9grx1rQNN0h/DUzmjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBQLCJLiN2O2plsu2/8A6vqvh0hPMjAKBggqhkjOPQQD
          AgNHADBEAiBN4qOtzNTAqDEjq55DUqdeUQQaLy6yHi5n2sW0GP97iwIgENsOkTn3
          XU5CAJB66DDtt4/UHmWUyN6eRwHDokJE2Qs=
          -----END CERTIFICATE-----

    httpOptions:
      verify: false
