---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUfyvAz+oAZa786bLnvVEqsMCbWocwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMDgwODQxMDBaFw0zNTEyMDUwODQxMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATMANcw+B108QCf
          PTGkL6cZCA/kYbzsVw7MHoDZR/gjSSCe1Mv3p+JIKLiT2CbxijXFZR+OoD6eq+Nz
          oCrfrFxVo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUSozy8pCrb9juY73JqqOKxjdzCbMwCgYIKoZIzj0EAwIDRwAwRAIg
          YO6Cb/R0OUHRol7VZCaKVmr6tyULGGjG0DOICBdhJBwCIHM8KjfP82qiXYLqzgZR
          s+nWYWWsPpP6o1vHuDVVepz8
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://localhost:${P1PORT}
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUfyvAz+oAZa786bLnvVEqsMCbWocwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMDgwODQxMDBaFw0zNTEyMDUwODQxMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATMANcw+B108QCf
          PTGkL6cZCA/kYbzsVw7MHoDZR/gjSSCe1Mv3p+JIKLiT2CbxijXFZR+OoD6eq+Nz
          oCrfrFxVo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUSozy8pCrb9juY73JqqOKxjdzCbMwCgYIKoZIzj0EAwIDRwAwRAIg
          YO6Cb/R0OUHRol7VZCaKVmr6tyULGGjG0DOICBdhJBwCIHM8KjfP82qiXYLqzgZR
          s+nWYWWsPpP6o1vHuDVVepz8
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      hostnameOverride: peer1.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUfyvAz+oAZa786bLnvVEqsMCbWocwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMDgwODQxMDBaFw0zNTEyMDUwODQxMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATMANcw+B108QCf
          PTGkL6cZCA/kYbzsVw7MHoDZR/gjSSCe1Mv3p+JIKLiT2CbxijXFZR+OoD6eq+Nz
          oCrfrFxVo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUSozy8pCrb9juY73JqqOKxjdzCbMwCgYIKoZIzj0EAwIDRwAwRAIg
          YO6Cb/R0OUHRol7VZCaKVmr6tyULGGjG0DOICBdhJBwCIHM8KjfP82qiXYLqzgZR
          s+nWYWWsPpP6o1vHuDVVepz8
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
