---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHzCCAcWgAwIBAgIUJpD/QEErDPJdhh0/8/r/QRlQHx4wCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMDcwNjU4MDBaFw0zNTEyMDQwNjU4MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASNCvd+IFHs/TUJ
          JxSxSff7tZ6i4GV1PqwYSlyYeUzwPQxqG08FSCqSULK9iSZ3SZWrD47DKP+7eJQg
          qdR499YOo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQU27xDLmMKMx1yDFnpOnDGD5EGCukwCgYIKoZIzj0EAwIDSAAwRQIh
          AOwuIRLF9gBcw6zAqi/YxqBfeMW9Bmklk2eSarJX7iZCAiAPDW6TI4Osf+tRVPy0
          f2FdEn5dy+O//KrOUjW4NYQUMw==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://localhost:${P1PORT}
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHzCCAcWgAwIBAgIUJpD/QEErDPJdhh0/8/r/QRlQHx4wCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMDcwNjU4MDBaFw0zNTEyMDQwNjU4MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASNCvd+IFHs/TUJ
          JxSxSff7tZ6i4GV1PqwYSlyYeUzwPQxqG08FSCqSULK9iSZ3SZWrD47DKP+7eJQg
          qdR499YOo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQU27xDLmMKMx1yDFnpOnDGD5EGCukwCgYIKoZIzj0EAwIDSAAwRQIh
          AOwuIRLF9gBcw6zAqi/YxqBfeMW9Bmklk2eSarJX7iZCAiAPDW6TI4Osf+tRVPy0
          f2FdEn5dy+O//KrOUjW4NYQUMw==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      hostnameOverride: peer1.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICHzCCAcWgAwIBAgIUJpD/QEErDPJdhh0/8/r/QRlQHx4wCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMDcwNjU4MDBaFw0zNTEyMDQwNjU4MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASNCvd+IFHs/TUJ
          JxSxSff7tZ6i4GV1PqwYSlyYeUzwPQxqG08FSCqSULK9iSZ3SZWrD47DKP+7eJQg
          qdR499YOo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQU27xDLmMKMx1yDFnpOnDGD5EGCukwCgYIKoZIzj0EAwIDSAAwRQIh
          AOwuIRLF9gBcw6zAqi/YxqBfeMW9Bmklk2eSarJX7iZCAiAPDW6TI4Osf+tRVPy0
          f2FdEn5dy+O//KrOUjW4NYQUMw==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
