---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHzCCAcWgAwIBAgIUOR7TPR1djKKasXUf1jhi7mxelOAwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMjEwODAyMDBaFw0zNTEyMTgwODAyMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQa2U+JJv3k7BBf
          G77lCBEHApLu7iMMvXCfUd42S2OqvIAFAFIxeIQVSdv4XVXfykSf9Nye2JXOacFD
          telhjri6o0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUPMbbI3dsgwwKJaklEOnKFFnXNVswCgYIKoZIzj0EAwIDSAAwRQIh
          AIBHox/R8lDlGoXlbohuA1jB3lGQvIcbCQMay9Vv9My4AiAqn+ltBkcsx/a2ytn0
          3+3sNLKsn0fSgEdkzH5Hr/MhXw==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://localhost:10051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHzCCAcWgAwIBAgIUOR7TPR1djKKasXUf1jhi7mxelOAwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMjEwODAyMDBaFw0zNTEyMTgwODAyMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQa2U+JJv3k7BBf
          G77lCBEHApLu7iMMvXCfUd42S2OqvIAFAFIxeIQVSdv4XVXfykSf9Nye2JXOacFD
          telhjri6o0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUPMbbI3dsgwwKJaklEOnKFFnXNVswCgYIKoZIzj0EAwIDSAAwRQIh
          AIBHox/R8lDlGoXlbohuA1jB3lGQvIcbCQMay9Vv9My4AiAqn+ltBkcsx/a2ytn0
          3+3sNLKsn0fSgEdkzH5Hr/MhXw==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      hostnameOverride: peer1.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICHzCCAcWgAwIBAgIUOR7TPR1djKKasXUf1jhi7mxelOAwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMjEwODAyMDBaFw0zNTEyMTgwODAyMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQa2U+JJv3k7BBf
          G77lCBEHApLu7iMMvXCfUd42S2OqvIAFAFIxeIQVSdv4XVXfykSf9Nye2JXOacFD
          telhjri6o0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUPMbbI3dsgwwKJaklEOnKFFnXNVswCgYIKoZIzj0EAwIDSAAwRQIh
          AIBHox/R8lDlGoXlbohuA1jB3lGQvIcbCQMay9Vv9My4AiAqn+ltBkcsx/a2ytn0
          3+3sNLKsn0fSgEdkzH5Hr/MhXw==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
