---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUB0mZLoh3p4TqZJ0NN1ce4Z3t1hMwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMjE4MDkzNDAwWhcNMzUxMjE1MDkzNDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABD1z
          5fUb8zrW/NtMopK4L6fpXq+U+rGCbRiXGL0FDJjyM4nuOzZGsWZ0HHLlg/IFxry3
          iObhRUpQ7qX5a0bmfzmjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBTnjj9N1xk56QOBQaM4AijoGZh1PTAKBggqhkjOPQQD
          AgNHADBEAiAnu7Z86L4RGVVcqkQqLFa0hnvLs3MRxdna9OiZCsSH9QIgAJ4ercS7
          otShJIyATCEyC+eiwYpzEa0NwK4aaRppA2I=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
  peer1.org1.example.com:
    url: grpcs://localhost:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUB0mZLoh3p4TqZJ0NN1ce4Z3t1hMwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMjE4MDkzNDAwWhcNMzUxMjE1MDkzNDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABD1z
          5fUb8zrW/NtMopK4L6fpXq+U+rGCbRiXGL0FDJjyM4nuOzZGsWZ0HHLlg/IFxry3
          iObhRUpQ7qX5a0bmfzmjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBTnjj9N1xk56QOBQaM4AijoGZh1PTAKBggqhkjOPQQD
          AgNHADBEAiAnu7Z86L4RGVVcqkQqLFa0hnvLs3MRxdna9OiZCsSH9QIgAJ4ercS7
          otShJIyATCEyC+eiwYpzEa0NwK4aaRppA2I=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      hostnameOverride: peer1.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUB0mZLoh3p4TqZJ0NN1ce4Z3t1hMwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMjE4MDkzNDAwWhcNMzUxMjE1MDkzNDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABD1z
          5fUb8zrW/NtMopK4L6fpXq+U+rGCbRiXGL0FDJjyM4nuOzZGsWZ0HHLlg/IFxry3
          iObhRUpQ7qX5a0bmfzmjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBTnjj9N1xk56QOBQaM4AijoGZh1PTAKBggqhkjOPQQD
          AgNHADBEAiAnu7Z86L4RGVVcqkQqLFa0hnvLs3MRxdna9OiZCsSH9QIgAJ4ercS7
          otShJIyATCEyC+eiwYpzEa0NwK4aaRppA2I=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
