---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUYgMDEbYXKsmhEkWi3dmjbrLGGSowCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDExMjMxMTMzMDBaFw0zNTExMjAxMTMzMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARk7v2QIwAI6QS8
          NLw+CGZpog+no3W19GKVY7KlSiQ31C2VcUTvHCUVyfnXv0UwwcHs1Tebgl7BtJuM
          +XmmA+6Yo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUrv5albYCOZJ2JjtjvX3cnbS1ksswCgYIKoZIzj0EAwIDRwAwRAIg
          BMPOoJpIPXX333McbYrdFajGuNlfNe6WFau8DZA29XsCIB4P7FTgBDp+I4GrStc0
          k1lkfzl5YUUWb6Rfd78nLgs9
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://localhost:${P1PORT}
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUYgMDEbYXKsmhEkWi3dmjbrLGGSowCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDExMjMxMTMzMDBaFw0zNTExMjAxMTMzMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARk7v2QIwAI6QS8
          NLw+CGZpog+no3W19GKVY7KlSiQ31C2VcUTvHCUVyfnXv0UwwcHs1Tebgl7BtJuM
          +XmmA+6Yo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUrv5albYCOZJ2JjtjvX3cnbS1ksswCgYIKoZIzj0EAwIDRwAwRAIg
          BMPOoJpIPXX333McbYrdFajGuNlfNe6WFau8DZA29XsCIB4P7FTgBDp+I4GrStc0
          k1lkfzl5YUUWb6Rfd78nLgs9
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      hostnameOverride: peer1.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUYgMDEbYXKsmhEkWi3dmjbrLGGSowCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDExMjMxMTMzMDBaFw0zNTExMjAxMTMzMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARk7v2QIwAI6QS8
          NLw+CGZpog+no3W19GKVY7KlSiQ31C2VcUTvHCUVyfnXv0UwwcHs1Tebgl7BtJuM
          +XmmA+6Yo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUrv5albYCOZJ2JjtjvX3cnbS1ksswCgYIKoZIzj0EAwIDRwAwRAIg
          BMPOoJpIPXX333McbYrdFajGuNlfNe6WFau8DZA29XsCIB4P7FTgBDp+I4GrStc0
          k1lkfzl5YUUWb6Rfd78nLgs9
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
