---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUaGLHiYFRRhEYhere5oKyD7UzGhswCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMjA4MDg0MTAwWhcNMzUxMjA1MDg0MTAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDmF
          rj6RGYTe/YqYbcb6RN1GrPJ8l3IVEbXcrchg7KCt1ZLB7wlsaQU1L4A36jTRmn8I
          WYtV7mPIuy2HF1WkhXejRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBTHbaOLzxPeiWF+zHCNedMyUHT/MDAKBggqhkjOPQQD
          AgNIADBFAiEAtcrIZEqYAq/TjpLqq1rm59Pzqve8s+bWvjN3h1f+p6MCICQvAbeo
          776rdileFKKcdI7pz3PgUBz09IEAegqL+2Vf
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
  peer1.org1.example.com:
    url: grpcs://localhost:${P1PORT}
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUaGLHiYFRRhEYhere5oKyD7UzGhswCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMjA4MDg0MTAwWhcNMzUxMjA1MDg0MTAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDmF
          rj6RGYTe/YqYbcb6RN1GrPJ8l3IVEbXcrchg7KCt1ZLB7wlsaQU1L4A36jTRmn8I
          WYtV7mPIuy2HF1WkhXejRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBTHbaOLzxPeiWF+zHCNedMyUHT/MDAKBggqhkjOPQQD
          AgNIADBFAiEAtcrIZEqYAq/TjpLqq1rm59Pzqve8s+bWvjN3h1f+p6MCICQvAbeo
          776rdileFKKcdI7pz3PgUBz09IEAegqL+2Vf
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      hostnameOverride: peer1.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUaGLHiYFRRhEYhere5oKyD7UzGhswCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMjA4MDg0MTAwWhcNMzUxMjA1MDg0MTAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDmF
          rj6RGYTe/YqYbcb6RN1GrPJ8l3IVEbXcrchg7KCt1ZLB7wlsaQU1L4A36jTRmn8I
          WYtV7mPIuy2HF1WkhXejRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBTHbaOLzxPeiWF+zHCNedMyUHT/MDAKBggqhkjOPQQD
          AgNIADBFAiEAtcrIZEqYAq/TjpLqq1rm59Pzqve8s+bWvjN3h1f+p6MCICQvAbeo
          776rdileFKKcdI7pz3PgUBz09IEAegqL+2Vf
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
