---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUM6z6bmrvRGFx7uqht4X0haUWP3QwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMTgwOTM0MDBaFw0zNTEyMTUwOTM0MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASceirXalMapAPw
          XNxtn0cIAnjJ/AlJDtSxgg1hKoA3sqH0iiHbRggXJJT5KWlTJO6dhM265AnAmEtO
          WwOQWzjSo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUN7ZjA8PImdl1Eja8bkpLXYyktVwwCgYIKoZIzj0EAwIDRwAwRAIg
          bH1vNm1dGtrFFqWoX1UF35v5Kaf1MSyexd69APTWy34CIGgDzBPr1L62Y0TKMpQy
          ShN4cbguMyqI0WRjWA+ULS4I
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://localhost:10051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUM6z6bmrvRGFx7uqht4X0haUWP3QwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMTgwOTM0MDBaFw0zNTEyMTUwOTM0MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASceirXalMapAPw
          XNxtn0cIAnjJ/AlJDtSxgg1hKoA3sqH0iiHbRggXJJT5KWlTJO6dhM265AnAmEtO
          WwOQWzjSo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUN7ZjA8PImdl1Eja8bkpLXYyktVwwCgYIKoZIzj0EAwIDRwAwRAIg
          bH1vNm1dGtrFFqWoX1UF35v5Kaf1MSyexd69APTWy34CIGgDzBPr1L62Y0TKMpQy
          ShN4cbguMyqI0WRjWA+ULS4I
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      hostnameOverride: peer1.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUM6z6bmrvRGFx7uqht4X0haUWP3QwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMDEyMTgwOTM0MDBaFw0zNTEyMTUwOTM0MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASceirXalMapAPw
          XNxtn0cIAnjJ/AlJDtSxgg1hKoA3sqH0iiHbRggXJJT5KWlTJO6dhM265AnAmEtO
          WwOQWzjSo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUN7ZjA8PImdl1Eja8bkpLXYyktVwwCgYIKoZIzj0EAwIDRwAwRAIg
          bH1vNm1dGtrFFqWoX1UF35v5Kaf1MSyexd69APTWy34CIGgDzBPr1L62Y0TKMpQy
          ShN4cbguMyqI0WRjWA+ULS4I
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
